"""

Revision ID: 0dc13fe0e2cc
Revises: 3ac41e715056
Create Date: 2025-12-17 16:32:36.836651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dc13fe0e2cc'
down_revision: Union[str, Sequence[str], None] = '3ac41e715056'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seeker_profiles', sa.Column('major', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seeker_profiles', 'major')
    # ### end Alembic commands ###
