"""

Revision ID: 3ac41e715056
Revises: a3ba006a60a3
Create Date: 2025-12-17 14:46:43.363546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ac41e715056'
down_revision: Union[str, Sequence[str], None] = 'a3ba006a60a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing_roommates', sa.Column('major', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listing_roommates', 'major')
    # ### end Alembic commands ###
